Add new article: "Open source"
dzcode-io/dzcode.io pull request #189
Opened 2020-09-18 20:39 UTC by NurElHuda

I've added a new article about Open source to the articles section

## Checklist

- [ ] `yarn test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://github.com/dzcode-io/dzcode.io/blob/master/.github/CONTRIBUTING.md#coding-guidelines)
- [x] Affected `data`
- [ ] Affected `frontend`

2020-09-19 11:20 UTC, Souhaib-Benbouzid requested changes
Amazing article, can you please.
- capitalize as Open_Source in https://github.com/dzcode-io/dzcode.io/blob/master/data/articles/list.json 
- add it to ssr.json https://github.com/dzcode-io/dzcode.io/blob/master/data/articles/ssr.json

2020-09-19 13:27 UTC, NurElHuda commented
@Souhaib-Benbouzid How about this? 
There is a change in the package.json, it was a consequence of pre-commit hooks. Should I leave it? or remove it?

2020-09-19 13:39 UTC, ZibanPirate requested changes
both files `package-lock.json` and `package.json` shouldn't be in the changes, this ususally happens when you run `git merge` instead of `git pull`

if possible you can:
- undo your changes on your local branch or stash them
- after [configuring a remote that points to the upstream (original) repository](https://docs.github.com/en/articles/configuring-a-remote-for-a-fork) instead of [merging upstream master to your local master](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork), pull from it instead (`git pull upstream/master`, or use `git rebase upstream/master`.

2020-09-19 13:40 UTC, ZibanPirate commented
i will add a proper documentation on how to sync old forked repos soon

2020-09-19 14:34 UTC, NurElHuda commented
@ZibanPirate Understood. I'll keep that in mind next time.

Also, I've removed the unwated files.

2020-09-19 14:37 UTC, ZibanPirate approved these changes
Solid work, that was quick 👌🏽

2020-09-22 10:01 UTC, Souhaib-Benbouzid requested changes
solid work, great article. review the requested changes, please

2020-09-22 18:34 UTC, NurElHuda commented on data/articles/list.json
> +    "The_Using_Of_Conventional_Commits_To_Contribute_To_DZCode",
Because I added a new item to the array, I had to add a comma at the end of the last item

2020-09-22 18:35 UTC, NurElHuda commented on data/articles/ssr.json
> +    "The_Using_Of_Conventional_Commits_To_Contribute_To_DZCode",
Because I added a new item to the array, I had to add a comma at the end of the last item

2020-09-23 11:26 UTC, Souhaib-Benbouzid approved these changes

2020-09-23 11:26 UTC, merged