180 update articles page content
dzcode-io/dzcode.io pull request #209
Opened 2020-10-09 19:57 UTC by Souhaib-Benbouzid

Implements #180 

- [x] Affected `data`
- [ ] Affected `frontend`

2020-10-09 21:39 UTC, NurElHuda commented on data/articles/Send_Emails_With_Django_and_Gmail_A_Better_Way/content.md
>  ## What i really want talk about
What I really want to talk about

2020-10-09 21:40 UTC, NurElHuda commented on data/articles/Send_Emails_With_Django_and_Gmail_A_Better_Way/content.md
> +this will not work , when your website is live u will get a lot of errors.
This will not work, if your website is live you will get a lot of errors.

2020-10-09 21:50 UTC, NurElHuda requested changes
There are a few typos, I've commented them with thier respective fix.

2020-10-10 09:10 UTC, Souhaib-Benbouzid commented
> There are a few typos, I've commented them with thier respective fix.

all corrected. thank you

2020-10-10 09:33 UTC, ZibanPirate approved these changes

2020-10-10 19:55 UTC, merged