* 404 error page.
dzcode-io/dzcode.io pull request #213
Opened 2020-10-09 21:35 UTC by NurElHuda

Add a component that handles 404 error.
Implements #107 

This is a screenshot of the result:
![image](https://user-images.githubusercontent.com/30445189/95633021-b8f2a980-0a7e-11eb-8184-a3405863848f.png)

I was going for a more clean design like: 
![image](https://user-images.githubusercontent.com/30445189/95633077-d3c51e00-0a7e-11eb-897d-76f89aca934b.png)

However, It needs refactoring of the Main component with its Switch and Routing. So, do I go all the way? or do I leave like this?

Another issue is that it only catches unfound paths that did not get matched by previous routs. So, a path like "/Learn/Git_Bas" or "/Articles/Send_Emails_With_D" does not get handled. Any ideas on how should I handle that?

## Checklist

- [ ] Affected `data`
- [ x] Affected `frontend`

2020-10-10 06:13 UTC, ZibanPirate requested changes
The current implementation is fine, still look clean at the same time user still can navigate to any section of the website.

as for the nested paths issue, this is out of this PR scope, since when we have wrong article link, we should redirect to `/Articles` url, and add a landing page for it, that being said, we can still fix it as part of #107 

the experience will be simular to zakiii.com
where going to
https://www.zakiii.com/Articles/My_2019_in_Review
is fine, but when going to a wrong link
https://www.zakiii.com/Articles/My_2020_in_Review
will redirect you to 
https://www.zakiii.com/Articles
with a nice landing page that tell you to browse articles from the sidebar.

for doing this, we need to change two things
- when we fetch the article, when call fails or we get a 404 response, we force redirect to `/Articles`, that can be done [here](https://github.com/dzcode-io/dzcode.io/blob/master/frontend/src/apps/main/redux/actions/articles-page/index.ts) where we check if response if good, if not we throw an exception [here](https://github.com/dzcode-io/dzcode.io/blob/master/frontend/src/apps/main/redux/actions/articles-page/index.ts#L74), and lastly we redirect to `/Articles` on the `catch` block [here](https://github.com/dzcode-io/dzcode.io/blob/master/frontend/src/apps/main/redux/actions/articles-page/index.ts#L86)
- second thing to do is adding a landing page for `/Articles`, that can be done [here](https://github.com/dzcode-io/dzcode.io/blob/master/frontend/src/apps/main/pages/articles/index.tsx#L41) where we add a sub-page similar to [content](https://github.com/dzcode-io/dzcode.io/tree/master/frontend/src/apps/main/pages/articles/content) sub-page but with a static content instead

Both these points can be done separately in two PRs as part of #107 , i can help out in one of them or you can do both, the exact same thing applies for `/Learn` btw.

2020-10-13 18:06 UTC, NurElHuda commented on frontend/src/apps/main/entry/index.tsx
> +const NotFound = lazy(() => import("t9/apps/main/pages/notFound"));
I've renamed the file to be snaked case.

2020-10-13 18:08 UTC, NurElHuda commented
I agree with separating the PRs. 
I will take care of them both.

2020-10-13 18:19 UTC, ZibanPirate approved these changes
That also works 👌🏽 thanks for the changes @NurElHuda

2020-10-13 18:21 UTC, merged