AlgerianAdministrativeDivision project added to dzcode.io
dzcode-io/dzcode.io pull request #225
Opened 2020-10-17 09:42 UTC by mohsenuss91

# Description
[AlgerianAdministrativeDivision ](https://github.com/mohsenuss91/AlgerianAdministrativeDivision) project added to [dzcode.io](https://github.com/dzcode-io) based on [dzcode.io article](https://www.dzcode.io/Articles/How_To_Add_Your_Project_To_DzCode/).

2020-10-17 12:15 UTC, ZibanPirate requested changes
Thank you @mohsenuss91 for submitting your awesome project, i have two small requests, and your PR will be ready to merge:
- Thanks for the link fixes, but please revert back the last two commits, cuz they are not related to submitting your project, and if you'd like, create a seperate PR for them and will merge it right away.
- run `yarn lint:fix` to fix pipeline error, then commit the changes

2020-10-18 10:12 UTC, mohsenuss91 commented
> Thank you @mohsenuss91 for submitting your awesome project, i have two small requests, and your PR will be ready to merge:
> 
> * Thanks for the link fixes, but please revert back the last two commits then force push, cuz they are not related to submitting your project, and if you'd like, create a seperate PR for them and will merge it right away.
> * run `yarn lint:fix` to fix pipeline error, then commit the changes

* Two commits reverted.
* but when I run `yarn lint:fix`  I've got this errors:
`$ yarn lint:fix
yarn run v1.22.5
$ concurrently "cd fullstack && yarn eslint:fix && yarn prettier:fix" "cd data &
& yarn eslint:fix && yarn prettier:fix" "cd frontend && yarn eslint:fix && yarn
prettier:fix"
'concurrently' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
`

2020-10-18 10:35 UTC, ZibanPirate commented
i see, it's fine @mohsenuss91, just run these commands step by step, and it should work fine:

1 - revert the last 4 commits, until you reach the first commit, do that by running this command **4 times**
```sh
git reset HEAD~
```
2 - clear your changes
```sh
git reset --hard
```
3 - make sure to install all dependencies
```sh
yarn
```
4 - fix linting errors
```sh
yarn lint:fix
```
5 - commit your changes
```sh
git add *
git commit -m "fixed linting errors"
```
6 - finally, force push your changes
```sh
git push -f
```

2020-10-18 14:16 UTC, mohsenuss91 commented
> i see, it's fine @mohsenuss91, just run these commands step by step, and it should work fine:
> 
> 1 - revert the last 4 commits, until you reach the first commit, do that by running this command **4 times**
> 
> ```shell
> git reset HEAD~
> ```
> 
> 2 - clear your changes
> 
> ```shell
> git reset --hard
> ```
> 
> 3 - make sure to install all dependencies
> 
> ```shell
> yarn
> ```
> 
> 4 - fix linting errors
> 
> ```shell
> yarn lint:fix
> ```
> 
> 5 - commit your changes
> 
> ```shell
> git add *
> git commit -m "fixed linting errors"
> ```
> 
> 6 - finally, force push your changes
> 
> ```shell
> git push -f
> ```

@ZibanPirate Done. Thanks for your help!

2020-10-18 14:29 UTC, ZibanPirate requested changes
That's great, one last change request and will merge your PR, to properly display your project, please apply the suggested changes i mentioned in the thread

2020-10-18 14:29 UTC, ZibanPirate commented on data/projects/Algerian_Administrative_Division/info.json
> +  "title": "AlgerianAdministrativeDivision",
```suggestion
  "title": "Algerian Administrative Division",
```

2020-10-18 14:29 UTC, ZibanPirate commented on data/projects/Algerian_Administrative_Division/info.json
> +  "githubURI": "https://github.com/mohsenuss91/AlgerianAdministrativeDivision",
```suggestion
  "githubURI": "mohsenuss91/AlgerianAdministrativeDivision",
```

2020-10-18 14:29 UTC, ZibanPirate commented on data/projects/Algerian_Administrative_Division/info.json
> +  "image": "https://github.com/mohsenuss91/AlgerianAdministrativeDivision/blob/master/assets/images/AlgerianAdministrativeDivision%20logo%20svg.svg"
```suggestion
  "image": "https://raw.githubusercontent.com/mohsenuss91/AlgerianAdministrativeDivision/master/assets/images/AlgerianAdministrativeDivision%20logo%20svg.svg"
```

2020-10-18 14:29 UTC, ZibanPirate commented on data/projects/list.json
> +    "AlgerianAdministrativeDivision"
```suggestion
    "Algerian_Administrative_Division"
```

2020-10-18 14:29 UTC, ZibanPirate commented on data/projects/ssr.json
> +    "AlgerianAdministrativeDivision"
```suggestion
    "Algerian_Administrative_Division"
```

2020-10-19 07:30 UTC, mohsenuss91 commented
> That's great, one last change request and will merge your PR, to properly display your project, please apply the suggested changes i mentioned in the thread

Done! 👍

2020-10-19 07:37 UTC, ZibanPirate approved these changes
Great, thanks for submitting your project! It will be in the website in the next release!

2020-10-19 07:37 UTC, merged

2020-10-19 08:15 UTC, mohsenuss91 commented
@ZibanPirate Thanks for your help! 👍🏻

2020-11-10 17:06 UTC, mohsenuss91 commented
> Great, thanks for submitting your project! It will be in the website in the next release!

Hey @ZibanPirate! 👋
The project still doesn't show upin dzcode.io website! 😔

2020-11-13 07:07 UTC, ZibanPirate commented
Hi @mohsenuss91 , the project is only added to [dzcode.io/Projects](https://www.dzcode.io/Projects), i created a PR ( #238 ) to add it also on the landing page, thanks for notice!

2020-11-13 16:19 UTC, mohsenuss91 commented
@ZibanPirate  Thanks for your help!