216 search functionalities
dzcode-io/dzcode.io pull request #229
Opened 2020-10-22 21:38 UTC by NurElHuda

# Description

Adds search through the website.
Implements #216

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

2020-10-23 17:07 UTC, Souhaib-Benbouzid commented on frontend/src/apps/main/redux/reducers/articles-page/index.ts
> +  console.log(state);
remove this console log please

2020-10-23 17:09 UTC, Souhaib-Benbouzid commented on frontend/src/apps/main/components/navbar/index.tsx
> +import IosSwitch from "./ios-switch";
run yarn lint:fix to sort this imports.

2020-10-23 17:10 UTC, Souhaib-Benbouzid requested changes
good work, please review the comments I left.

2020-10-23 21:13 UTC, NurElHuda commented on frontend/src/apps/main/components/navbar/index.tsx
> +import IosSwitch from "./ios-switch";
yes, I have used it. But it isn't working. It isn't fixing the sort errors. It just flags the errors but don't fix them.

2020-10-24 14:51 UTC, NurElHuda commented on frontend/src/apps/main/redux/reducers/articles-page/index.ts
> +  console.log(state);
Done.

2020-10-24 14:51 UTC, NurElHuda commented on frontend/src/apps/main/components/navbar/index.tsx
> +import IosSwitch from "./ios-switch";
I've fixed it.

2020-10-24 14:54 UTC, NurElHuda commented
This pull request adds a search input component to the nav-bar. The search doesn't work just yet.
This is the first part of implementing the search functionalities.

2020-10-25 07:12 UTC, ZibanPirate commented
Understood 👌🏽, later we will add and API endpoint for search, only then you can integrate both stacks

2020-12-30 18:43 UTC, ZibanPirate commented
thanks again for the PR @NurElHuda , unfortunately we now switched default branch to `main` and made breaking changes, from now on, all PRs should be against `main`, so please close this PR and if you have time, create a new one against `main`

2021-04-02 10:44 UTC, ZibanPirate commented
i'm closing this for now @NurElHuda , we can always cherry pick some commit from here when needed

2021-04-02 10:44 UTC, closed without merging