style front: fix typos & punctuation
dzcode-io/dzcode.io pull request #240
Opened 2020-12-27 01:23 UTC by Noisy96

# Description
This PR fixes various typos, missed punctuation and letter case.

## Type of change
Minor typos fixes

## Remarks
* I took the liberty to include fixes in articles descriptions (which I suppose would usually require original author's review) because I believe the changes did not affect the meaning and only dealt with language.

2020-12-27 09:19 UTC, ZibanPirate requested changes
Thank you @Noisy96 for the changes, i opened one thread about the "library" word, i suggested to use "software" instead as it's a more general term.

2020-12-27 09:19 UTC, ZibanPirate commented on frontend/src/apps/main/pages/landing/what-and-why/index.tsx
> +      "Bringing your project to the spotlight and letting local collaborators find you, which will lead to an even better version of your library.",
yes i agree with you, i think "software" would better better fitted word, what do u think?
```suggestion
      "Bringing your project to the spotlight and letting local collaborators find you, which will lead to an even better version of your software.",
```

2020-12-27 19:28 UTC, Noisy96 commented on frontend/src/apps/main/pages/landing/what-and-why/index.tsx
> +      "Bringing your project to the spotlight and letting local collaborators find you, which will lead to an even better version of your library.",
Yes, perfect :thumbsup:
it even covers datasets, according to some defintions [1](https://en.wikipedia.org/wiki/Software) [2](https://searchapparchitecture.techtarget.com/definition/software)

2020-12-28 06:43 UTC, ZibanPirate approved these changes
Solid work @Noisy96 , thanks for the fixes!

2020-12-28 06:44 UTC, merged