migrate new GitHub users API
dzcode-io/dzcode.io pull request #290
Opened 2021-04-10 16:00 UTC by well-balanced

# Description

Implements #286

- Call `v2/GithubUsers/{username}` from the frontend
- Remove the old API `/github/users`

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ✔️ ] New feature (non-breaking change which adds functionality)

2021-04-10 17:39 UTC, ZibanPirate requested changes
this is a well written PR, couple more changes suggested, and we good to go 👌🏽

2021-04-10 17:39 UTC, ZibanPirate commented on api/src/github-user/types.ts
> +export class GetContributorsResponseDto extends GeneralResponseDto {
i believe you forgot to remove the copied code from line 7 to 11 ;)

2021-04-10 17:39 UTC, ZibanPirate commented on api/src/github-user/controller.ts
> +    const user = plainToClass(GithubUserDto, {
there is no need to verify a service response, so the code from line 25 to 27 can be removed as well as on line 7

2021-04-10 17:39 UTC, ZibanPirate commented on api/src/github/service.ts
> +      `https://api.github.com/users/${username}`,
oops, DRY ;)

```suggestion
      `${this.apiURL}/users/${username}`,
```

2021-04-10 17:58 UTC, well-balanced commented on api/src/github/service.ts
> +      `https://api.github.com/users/${username}`,
oops 😂

2021-04-10 18:37 UTC, well-balanced commented on api/src/github-user/controller.ts
> +    const user = plainToClass(GithubUserDto, {
yesss! I've just fixed it. 
but can I ask a question? I added these lines for documentation. if I do not specify class object like a `GithubUserDto` into `ResponseDto`, I couldn't see any details in `http://localhost:7070/v2/docs/` are there any issues when a user object is wrapped in a DTO object? It should be tiresome, but I would be learned lots of things from your reply :)

2021-04-10 19:02 UTC, ZibanPirate requested changes
one last change and we're good to go!

2021-04-10 19:02 UTC, ZibanPirate commented on api/src/github-user/types.ts
> +  @ValidateNested({ each: true })
Since user is only one object, and not an array, `{ each: true }` option is not needed, otherwise it will showup as an array in swagger docs :p

```suggestion
  @ValidateNested()
```

2021-04-10 19:02 UTC, ZibanPirate commented on api/src/github-user/types.ts
> +  user?: GitHubUserApiResponse;
as mentioned in my first comment, use needs to be a dto class in order to show up on swagger docs

```suggestion
  user?: GithubUserDto;
```

2021-04-10 19:04 UTC, ZibanPirate commented on api/src/github-user/types.ts
> +import {} from "module";
also, this is a bit funny haha, didn't know if it's even possible !
```suggestion
```

2021-04-10 19:09 UTC, ZibanPirate commented on api/src/github-user/controller.ts
> +    const user = plainToClass(GithubUserDto, {
well, as i mentioned in the new comments, the nested objects inside the dto class has to be dto classes too, otherwise OpenApi will not pick them as specs in the docs, you also need to decorate them with `@ValidateNested()` (or `@ValidateNested({ each: true }) and @Type(() => YouClassDto)` for array of objects)

2021-04-11 01:35 UTC, well-balanced commented
```ts
Type 'GitHubUserApiResponse' is not assignable to type 'GithubUserDto'.
  Types of property 'id' are incompatible.
    Type 'number' is not assignable to type 'string'.
```

I think It's a conflict between `GithubUserDto` and `GitHubUserApiResponse`

```ts
export class GithubUserDto implements GithubUser {
  ...
  @IsString()
  id!: string;
  ...
}

export interface GitHubUserApiResponse {
  ...
  id: number;
  ...
}
```

2021-04-11 07:23 UTC, ZibanPirate requested changes
yes you're correct, we need to do 3 changes:

1. in `common/src/types/index.ts` change line 43 to:
```ts
  id: number;
```

2. in `api/src/github/dto.ts` change line 10 to:
```ts
  id!: number;
```

3. in `api/test/mocks.ts` change lines 6, 14 and 22 to:
```ts
  id: 1,
```

```ts
  id: 2,
```

```ts
  id: 3,
```

2021-04-11 15:10 UTC, well-balanced commented
@ZibanPirate I'm sorry to late 😭 I've just implemented earlier suggestion :)

2021-04-11 15:34 UTC, ZibanPirate approved these changes
no worries, thanks for your well balanced PR ;) merging ...

2021-04-11 15:35 UTC, merged