Feature: Adding articles screen
dzcode-io/dzcode.io pull request #364
Opened 2021-09-10 10:04 UTC by Omar-Belghaouti

# Description

This feature is dedicated to add articles screen in the mobile app, also to clean some dead code in mobile section.

Fixes #362 #348 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

2021-09-11 17:22 UTC, ZibanPirate requested changes
really awesome work @Omar-Belghaouti , tested locally, works like a charm.

just one small change to fix one annoying error message.

idk if you plan to keep this PR a draft and add things to it, or merge it and add followup PR, but in any case, these are the things that can to be done afterward:
- add some horizontal margins to the content
- text in dark mode is still black, it should be white i guess?
- once an article is fetched, we should fetch both authors and contributors and display their profiles below the article.

again, thanks a lot for this great code 🙏🏽

2021-09-11 17:22 UTC, ZibanPirate commented on mobile/src/screens/articles/article-details/ui/article-details-screen.tsx
> +            {articles?.find((article) => article.slug === route.params.article.slug)?.content}
```suggestion
            {articles?.find((article) => article.slug === route.params.article.slug)?.content || ""}
```

this will fix this annoying error:

![3CFBAE3D-A1C2-476E-B068-5F9A835D5364](https://user-images.githubusercontent.com/20110076/132955977-99812459-00ed-446d-9c45-7266220c7c22.PNG)

2021-09-11 18:05 UTC, Omar-Belghaouti commented on mobile/src/redux/actions/articles-page/index.ts
> +          articles: articles?.map((article) => (article.slug === slug ? json : article)),
Thanks @ZibanPirate appreciate it!

2021-09-11 18:05 UTC, Omar-Belghaouti commented on mobile/src/redux/reducers/articles-page/index.ts
> +      return { ...state, ...action.payload };
Glad you liked it!

2021-09-11 18:06 UTC, Omar-Belghaouti commented on mobile/src/screens/articles/article-details/ui/article-details-screen.tsx
> +            {articles?.find((article) => article.slug === route.params.article.slug)?.content}
@ZibanPirate okay, thanks for this, I will do it.

2021-09-11 18:08 UTC, Omar-Belghaouti commented
@ZibanPirate thanks for you comments, this PR is still a WIP and I am planning to change the project structure as we spoke in #362  when I finish these changes I'll ask for your review again.

2021-09-12 08:52 UTC, ZibanPirate approved these changes
awesome work @Omar-Belghaouti , works perfectly on my machine.

i added couple more tasks in #362 , i'm currently doing a followup PR to this one to address the newly added tasks

2021-09-12 09:09 UTC, merged