Chore: Using relative imports in mobile codebase
dzcode-io/dzcode.io pull request #491
Opened 2022-09-16 18:06 UTC by omdxp

# Description

This PR is dedicated to use relative imports in the mobile codebase.

## Type of change

- I'm not sure

2022-09-16 21:25 UTC, ZibanPirate requested changes
we could use [eslint-plugin-import/no-relative-parent-imports](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-relative-parent-imports.md) to prevent future use of relative imports.

the `yarn.lock` should not change, make sure you rebase from `main` and run `yarn install` from the root

2022-09-16 21:25 UTC, ZibanPirate commented on mobile/babel.config.js
> +      ],
hmm, isn't this a bit confusing, how would you (as a confused new contributor) know which of these directories to import from without looking at this file?

I feel more confident when typing just `src/` and then I get all the auto-completion for the directories. There's no harm in keeping the `src/` in each import right?

- it makes a clear seperation between npm packages and actual directories inside `./src`.
- the code is more readable using `src/`.
- we don't have to make any changes if we change the folder structure.
- when moving files or renaming them, things will go wide when typescript tries to help you automatically refactor all the imports (it will suggest `src/` by default, then you end up with a mix of both)

```suggestion
```

2022-09-16 21:25 UTC, ZibanPirate commented on mobile/src/components/index.tsx
> +export { TryAgain } from "./try-again";
I don't think it is a good idea, consuming any of these component will unnecessarily load all the javascript for the other components, let's tree-shake 'em

2022-09-16 21:25 UTC, ZibanPirate commented on mobile/src/config/index.ts
> +});
whaayyyhhh
```suggestion
export const fullstackConfig = fsConfig(getEnv(), { hostname: process.env.LOCAL_API_HOST });
```

2022-09-16 21:25 UTC, ZibanPirate commented on mobile/src/screens/articles/article-details/index.tsx
> +import { DZCodeLoading, ErrorBoundary, TryAgain } from "components";
as clean as this looks, it is not tree-shakable and can lead to big bundle sizes

2022-09-16 21:25 UTC, ZibanPirate commented on mobile/tsconfig.json
> +    }
`baseUrl` this will suffice if we use `src/` in imports
```suggestion
    "baseUrl": "."
```

2022-09-16 21:48 UTC, omdxp commented on mobile/babel.config.js
> +      ],
Yeah make sense. I'll prefix the imports with `src/`

2022-09-16 21:52 UTC, omdxp commented on mobile/src/config/index.ts
> +});
It seems prettier did this change 😅 I didn't notice

2022-09-17 08:23 UTC, ZibanPirate requested changes
added one more comment, and there's still some unresolved stuff in https://github.com/dzcode-io/dzcode.io/pull/491#pullrequestreview-1111220018.

Tests are failing btw

2022-09-17 08:23 UTC, ZibanPirate commented on mobile/package.json
> +    "start:dev": "expo start --clear",
let's not clear each time, it will slowdown the boottime.

```suggestion
    "start:dev": "expo start",
    "start:dev:fresh": "expo start --clear",
```

2022-09-17 09:55 UTC, ZibanPirate commented on mobile/package.json
> +    "url": "https://omar-belghaouti.web.app"
Hmm just an idea, how about we have https://omar-belghaouti.dzcode.io ? we can setup unlimited subdomains under dzcode.io for free, and of course, you can point it to whatever website you have.

2022-09-17 09:56 UTC, omdxp commented on mobile/package.json
> +    "url": "https://omar-belghaouti.web.app"
That's so cool, I'd definitely like that!

2022-09-17 10:02 UTC, ZibanPirate commented on mobile/package.json
> +    "url": "https://omar-belghaouti.web.app"
added it to the google doc, we can discuss that later 👌🏽

2022-09-17 10:24 UTC, ZibanPirate approved these changes
Awesome work @omdxp , there is still some missing setup regarding the `eslint` rule for relative imports, but no worries, i will fix that myself in https://github.com/dzcode-io/dzcode.io/issues/492

2022-09-17 10:25 UTC, merged