Indexing models during cron job
dzcode-io/dzcode.io pull request #620
Opened 2024-12-21 15:51 UTC by omdxp

- Add `deleteAllDocuments` search service method.
- Index models that represent the contributions, contributors and projects.

- [ ] Bug fix
- [x] New feature
- [ ] Other

2024-12-21 17:16 UTC, ZibanPirate requested changes
your suggested way is:
1- collect all documents to index in an array
2- bulk-delete all currently indexed documents from search db
3- bulk-index new documents from scratch into search db

meanwhile, this cron works slightly differently, where:
1- doesn't collect models, but instead upsert them on the spot to db
2- doesn't delete all models, but only outdated ones (runId is different)
3- doesn't have a third step

So, ... for the search implementation to follow along with this cron implementation it should:
1- index (upsert) each document on the spot, don't save it to an array and do that later.
2- bulk-delete all documents that are outdated (runId is different)

I added comments on how to do that

2024-12-21 17:16 UTC, ZibanPirate commented on api/src/digest/cron.ts
>                });
same here we index directly

```ts
await this.searchService.upsert("contributor", {...});
```

2024-12-21 17:16 UTC, ZibanPirate commented on api/src/digest/cron.ts
> +              });
and here too we index directly:

```ts
await this.searchService.upsert("contribution", {...});
```

2024-12-21 17:16 UTC, ZibanPirate commented on api/src/digest/cron.ts
> +      await this.searchService.deleteAllDocuments("contributor");
these should be:

```ts
await this.searchService.deleteAllButWithRunId("project", runId);
```

2024-12-21 17:16 UTC, ZibanPirate commented on api/src/digest/cron.ts
> +      await this.searchService.index("contributor", searchContributorItems);
then we don't need this section
```suggestion
```

2024-12-21 17:29 UTC, omdxp commented on api/src/digest/cron.ts
> +      await this.searchService.deleteAllDocuments("contributor");
In this case we don't need to delete at all from the search service since it's always upsetting the existing ones with the unique ID, also it won't make sense to delete these entries after upserting them in the engine's database

2024-12-21 17:45 UTC, ZibanPirate commented on api/src/digest/cron.ts
> +      await this.searchService.deleteAllDocuments("contributor");
these will not be deleted, because they have the current `runId`.

what will be deleted are the closed-issues and the merged-PRs, which won't be fetched during this cron job, these end up still in the database with the old `runId`, the only way we delete these old entries is to bulk-delete anything that have `runId` that is not the current `runId`

2024-12-21 17:48 UTC, omdxp commented on api/src/digest/cron.ts
> +      await this.searchService.deleteAllDocuments("contributor");
This seems specific to contributions only. So if I understood correctly, the contribution search item should include an id that is combined with `runId`?

2024-12-21 17:53 UTC, omdxp commented on api/src/digest/cron.ts
> +      await this.searchService.deleteAllDocuments("contributor");
I guess it's possible for every model, so the `id` should be something like `[runId]--XXX` and later on we remove `[runId]--` when creating links in FE

2024-12-21 17:54 UTC, ZibanPirate requested changes

2024-12-21 17:54 UTC, ZibanPirate commented on api/src/digest/cron.ts
> +        id: project.slug.replace(/[.]/g, "-"), // MeiliSearch doesn't allow dots in ids
let's move this logic up to a variable:
```ts
let sanitizedSlug = project.slug.replace(/[.]/g, "-");
```

then use it for both `projectsRepository.upsert` and `searchService.upsert`

so later when querying the search database we don't have to reverse map the id again.

2024-12-21 17:54 UTC, ZibanPirate commented on api/src/digest/cron.ts
> +                await this.contributorsRepository.upsert({
can we do this for all three models where:

we construct the object first
```ts
let contributorEntity = { /* all the mapping and stuff here... */ };
```
then reuse it for both database and search
```ts
await this.contributorsRepository.upsert(contributorEntity);
await this.searchService.upsert("contributor", contributorEntity)
```

2024-12-21 17:56 UTC, omdxp commented on api/src/digest/cron.ts
> +                await this.contributorsRepository.upsert({
It's not `SearchItem`

2024-12-21 18:00 UTC, omdxp commented on api/src/digest/cron.ts
> +      await this.searchService.deleteAllDocuments("contributor");
Or add `runId` property in `SearchItem`

2024-12-21 18:58 UTC, omdxp commented on api/src/digest/cron.ts
> +      await this.searchService.deleteAllDocuments("contributor");
The primary key of the document has to be unique per `id` and per `runId` so it can ensure that the indexation process is always up to date with added/deleted items

2024-12-21 20:08 UTC, ZibanPirate commented on api/src/digest/cron.ts
> +      await this.searchService.deleteAllDocuments("contributor");
> This seems specific to contributions only

all models, projects get deleted too, and contributors' accounts can be deleted too.
the first case happened few times already (projects deleted on Github while still listed in dzcode)

> has to be unique per id and per runId

No, runId is just a string field in the document, nothing special there. and it should not be in the document id.

2024-12-21 20:10 UTC, ZibanPirate commented on api/src/digest/cron.ts
> +                await this.contributorsRepository.upsert({
maybe more like:
```ts
await this.contributorsRepository.upsert(contributorEntity);
const { id, title, runId } = contributorEntity;
await this.searchService.upsert("contributor", { id, title, runId })
```

2024-12-21 20:16 UTC, omdxp commented on api/src/digest/cron.ts
> +      await this.searchService.deleteAllDocuments("contributor");
The primary key of the index is the `id` it has to be unique otherwise you cannot add [old]-item and [new]-item together

2024-12-21 20:19 UTC, omdxp commented on api/src/digest/cron.ts
> +                await this.contributorsRepository.upsert({
`runId` in the same scope, it's better to leave it as it is

2024-12-21 20:21 UTC, omdxp commented on api/src/digest/cron.ts
> +      await this.searchService.deleteAllDocuments("contributor");
During the data retrieval, the `runId--` part will be stripped out

2024-12-22 14:19 UTC, omdxp commented on api/src/digest/cron.ts
> +              const [{ id: contributorId }] =
we missed upserting search document for contributor here too

2024-12-22 14:19 UTC, omdxp commented on api/src/digest/cron.ts
> +      await this.searchService.deleteAllButWithRunId("contributor", runId);
we can promise.all here

2024-12-22 14:19 UTC, omdxp commented on packages/models/src/_base/index.ts
> +};
since we use ProjectEntity and `Entity`ies in general, we don't need this

2024-12-22 14:19 UTC, omdxp commented on api/src/search/service.ts
> +  public upsert = async <T extends BaseSearchItem>(
```suggestion
  public upsert = async <T extends BaseEntity>(
```

2024-12-22 14:19 UTC, omdxp commented on api/src/digest/cron.ts
>          ...project,
this is a bug, lets only destruct the field we need (eg: repositories are leaked, it should not be exposed outside Cron context)

```suggestion
        ...project,
```

2024-12-22 14:19 UTC, omdxp commented on api/src/digest/cron.ts
> +      const projectEntity = {
lets apply this suggestion to other entities as well:

```suggestion
      const projectEntity: ProjectRow = {
```

2024-12-22 15:48 UTC, ZibanPirate requested changes

2024-12-22 15:48 UTC, ZibanPirate commented on packages/models/src/_base/index.ts
> +  runId?: string;
let's instead fix the root cause by removing all `.default("initial-run-id")` assurances in the code, then putting `runId` back to being required
```suggestion
  runId: string;
```

2024-12-22 15:48 UTC, ZibanPirate commented on api/src/search/types.ts
> +type SearchItem = ProjectEntity | ContributionEntity | ContributorEntity;
```suggestion
export type SearchResults = MultiSearchResponse<ProjectEntity | ContributionEntity | ContributorEntity>;
```

2024-12-22 15:48 UTC, ZibanPirate commented on api/src/search/service.ts
> +    });
`createIndex` will throw if the index already exists, let's create our own `upsertIndex` method and call it instead:

```ts
  private upsertIndex = async (index: string): Promise<void> => {
    try {
      await this.meilisearch.getIndex(index);
      this.logger.info({ message: `${index} index already exists` });
    } catch {
      await this.meilisearch.createIndex(index, { primaryKey: "id" });
      this.logger.info({ message: `${index} index created` });
    }
  };
```

```suggestion
    await this.upsertIndex("project");
```

2024-12-22 15:50 UTC, omdxp commented on packages/models/src/_base/index.ts
> +  runId?: string;
this will cause a tsc error when upserting in the search service, because the inferred `*Row` has an optional `runId` which does not satisfy the `BaseEntity`

2024-12-22 16:32 UTC, ZibanPirate approved these changes
thank you a lot @omdxp ! one step forward to having search in the website

2024-12-22 16:33 UTC, merged